FROM williamyeh/ansible:debian8

WORKDIR /tmp
COPY  .  /tmp/ansible-certificates-manager

RUN echo 127.0.0.1 > inventory

RUN ansible-playbook -i inventory ansible-certificates-manager/tests/provision.yml --connection=local --sudo
